### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by lapptomi** [Tuupertunut/BattleSheepSolver#1]
*Projekti ladattu 13.00 03.12.2021.*  

# Vertaisarviointi  

Projektin dokumentaatio oli hyvin kirjoitettu ja sisälsi ohjeet mm. ohjelman suorittamiseen sekä testaamiseen liittyen.
Testikattavuusraportin luominen oli ilmeisesti myös automatisoitu Github Actionsin avulla, joka oli järkevästi tehty.

Koodin laatu oli yleisesti hyvää ja helposti luettavissa. Esimerkiksi kommentteja oli lisätty paljon sekä koodi oli tyyliltään laadukasta, eli ei sisältänyt käyttämätöntä koodia tai ylimääräisiä välilyöntejä / rivejä tms.  

Funktiot oli myös hyvin jaettu osiin ja tekivät vain yhtä asiaa, joten koodissa ei ollut ylipitkiä funktioita. 

Jos jostain pitäisi huomauttaa, niin projektissa ei ilmeisesti ole käytössä jonkinnäköistä linteriä / checkstyleä vastaavaa Rustille, joka oli kurssin materiaalissa suosituksena jo viikolle 3. 

Testit olivat myös ilmeisesti kirjoitettu samaan tiedostoon, kuin board.rs, joten olisiko testit projektin rakenteen puolesta parempi siirtää esimerkiksi omaan tiedostoon tai kansioon?

Tosin en tiedä Rustin yleisiä käytäntöjä, kun en ole riviäkään kirjoittanut sillä koodia, joten tämän takia hieman vaikea antaa mitään rakentavaa palautetta.

Yleisesti kuitenkin ohjelma oli toimiva sekä dokumentaatio ja koodi laadukasta.

**Comment by Tuupertunut** [comment]
Kiitos palautteesta. En tiedä Rustille mitään hyvää lintteriä, mutta suoritan rustfmt-koodiformatterin joka tallennuksella. Koodi on tällöin aina formatoitu rustfmt:n asetusten mukaisesti, ja se toimii ikään kuin manuaalisena lintterinä.

Testit taidan tosiaan siirtää erilliseen tiedostoon tai kansioon. Rustin virallinen käytäntö on laittaa yksikkötestit samaan tiedostoon testattavan koodin kanssa, mutta se on kyllä mielestäni aika huono käytäntö.
