### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by FinThunderstorm** [Tuupertunut/BattleSheepSolver#2]
Vertaisarvioitu commit `df02610`, ladattu 13.12.2021 klo 1030

## Havaintoja

- Rust vaikuttaa sopivalta kieleltä tähän tapaukseen. En ole aikasemmin Rustia itse käyttänyt, mutta koodia lukiessani törmäsin mielestäni viisaasti valittuihin tietorakenteisiin, sekä harkittuihin suunnitteluvalintohin. Sivuhuomiona toimivan Rust-koodin lukeminen ei vähentänyt mielenkiintoa kyseisen koodikielen kokeilemista kohtaan.
- BattleSheep vaikutti mielenkiintoiselta peliltä ja pelin idea on saatu hyvin siirrettyä koneella suoritettavaan muotoon!  
- Koodi vaikutti tässä vaiheessa jo hyvin optimoidulta, ja raporttien perusteella oli löydetty hyviä kohteita. Yllätyin itsekin lukiessani tästä 35-kertaisesta suorituskyvyn kasvusta lukiessani siitä.

## Kehityskohteita

- Voisiko käyttöliittymään lisätä pelilaudan lisäämisen jälkeen jokin pieni havainto, että "pelilauta ladattu, aloita suoritus"/"vahvista pelilauta" painamalla *enter*? Kuvittelin sovelluksen pyörineen tovin, mutta todellisuudessa mitään ei tapahtunutkaan. Naputeltuani muutaman kerran *enteriä* lähti sovellus pyörimään kivasti. Tämä lienee enemmän käyttäjävirhe, kun jälkikäteen huomasin maininnan käyttöohjeissa, mutta ei liene huono asia olla myös sovelluksen puolella mainintana.
- Testikattavuudesta havainto: olisiko kokonaisuuden kannalta järkevää myös testata `main.rs` puolella olevia ehtoja milloin käytetään heuristista arviota, ja palauttaako nämä funktiot tällöin oikean tuloksen? Samalla pohdin myös noiden kokonaisuuksien testaamista, palauttaako esimerkiksi `best_move` halutun pelilaudan tilanteen. Toki ne kutsuvat pääsääntöisesti `board.rs` tiedostossa testattuja tapauksia, mutta mietin asiaa isomman kuvan kautta.

**Comment by Tuupertunut** [comment]
Kiitos palautteesta. Minimax-algoritmin testaaminen onkin jo tehtävälistallani. Huomautuksen lisääminen käyttöliittymään ylimääräisestä tyhjästä rivistä on mainio kehitysehdotus. Syötteen loppuun on tosiaan pakko syöttää tyhjä rivi, koska muuten ei voisi tietää, milloin käyttäjä haluaa lisätä uuden rivin pelilautaan ja milloin suorittaa ohjelman.
